### ISSUE TITLE
InternalTests.testGit fails under Linux

### ISSUE THREAD

**Issue by felix91gr** [SDGGiesbrecht/SDGCommandLine#34]
### Description

This test fails under Linux. The test suite reveals the failing assert. After commenting that line, the test passes without a problem.

### Demonstration

I isolated the test, ran `swift test` and got this output:

```console
felix@felix-X550LD ~/D/P/A/sdgCommandLine> swift test
Compile Swift Module 'SDGCommandLineTests' (12 sources)
Linking ./.build/x86_64-unknown-linux/debug/SDGCommandLinePackageTests.xctest
Test Suite 'All tests' started at 2018-04-13 04:26:16.479
Test Suite 'debug.xctest' started at 2018-04-13 04:26:16.480
Test Suite 'InternalTests' started at 2018-04-13 04:26:16.480
Test Case 'InternalTests.testGit' started at 2018-04-13 04:26:16.480

$ git version
git version 2.7.4

Expected Git 2.15.1. Attempting to continue anyway...
/home/felix/Documents/Programming/AwesomeSystemSwift/sdgCommandLine/Tests/SDGCommandLineTests/All Tests/InternalTests.swift:98: error: InternalTests.testGit : XCTAssertTrue failed - 
Test Case 'InternalTests.testGit' failed (1.744 seconds)
Test Suite 'InternalTests' failed at 2018-04-13 04:26:18.224
	 Executed 1 test, with 1 failure (0 unexpected) in 1.744 (1.744) seconds
Test Suite 'debug.xctest' failed at 2018-04-13 04:26:18.224
	 Executed 1 test, with 1 failure (0 unexpected) in 1.744 (1.744) seconds
Test Suite 'All tests' failed at 2018-04-13 04:26:18.224
	 Executed 1 test, with 1 failure (0 unexpected) in 1.744 (1.744) seconds

```

### Availability to Help

I can point to the causes and help by running tests, if needed.

### Solution/Design Thoughts

Maybe my version of Git is too old. I can't upgrade it to the bleeding edge though, because I use Ubuntu 16.04's repositories.

The problem could be related to the fact that `FileManager.swift` is [incomplete in corelibs-foundation](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/FileManager.swift). [They're gonna finish `corelibs-foundation` someday, though](https://forums.swift.org/t/shouldn-t-foundation-give-off-warnings-when-nsunimplemented-is-bound-to-appear/11576/8?u=felix91gr). So not all hope's lost.

**Comment by SDGGiesbrecht** [comment]
[This](https://github.com/SDGGiesbrecht/SDGCommandLine/blob/master/Tests/SDGCommandLineTests/All%20Tests/InternalTests.swift#L98) is the test which is failing. The test is supposed to verify the ability to accurately detect files ignored by Git. It expects the existence of the `Validate (Linux).sh` script which Workspace should be creating for you when you run `Refresh (Linux).sh`. If that script has never been run, then the test would understandably fail. 

i.e. It will always fail on a fresh clone with just `swift test` instead of `workspace refresh` + `workspace validate`.

Do not close this until I have added a note to that effect to the test failure message.

**Comment by felix91gr** [comment]
> This is the test which is failing.

Yup, we're on the same line, but I should've been more explicit when I pointed the test out:

> The test suite reveals the failing assert. After commenting that line, the test passes without a problem.

> i.e. It will always fail on a fresh clone with just swift test instead of workspace refresh + workspace validate.

Awesome! Then this one's not a concern ^^ 

> Do not close this until I have added a note to that effect to the test failure message.

No problem :wink:

**Comment by SDGGiesbrecht** [comment]
Checks for `.build` instead now.
